### ISSUE TITLE
[Feature Request] Optional sorting by chronological, file size, & alphabetical options.

### ISSUE THREAD

**Issue by JasonHoku** [AlUlkesh/sd_search_model#2]
Chronological would be especially useful for those of us that love to test those new models that are coming out daily these days.

And thank you for this extension!

**Comment by AlUlkesh** [comment]
@JasonHoku This commit contains the sort option. Hope it works like you expected.

**Comment by JasonHoku** [comment]
It works great! Thank you!

**Comment by JasonHoku** [comment]
File size would be quite nice as well because often peoples largest models are their best/favorite models ^_^

**Comment by AlUlkesh** [comment]
Sure, no problem. Check the latest commit.

**Comment by JasonHoku** [comment]
Sheesh so fast haha - Thank you!!
