### ISSUE TITLE
Models don't switch after clicking radio button & Switch to/from one-line display doesn't do anything?

### ISSUE THREAD

**Issue by ese-s** [AlUlkesh/sd_search_model#4]
Im testing the 07258419b9752070bb798380e61d55d837206097 commit, the commit without the the ckpt-dir support and I'm not sure what the button "Switch to/from one-line display" is meant to do I saw your model in the show and tell section on the AUTOMATIC1111 web discussions tab (https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/6423) and you stated "_Results are filtered and the model can be directly loaded by clicking its radio button_" so I assumed a model would load after I pressed the radio button but nothing loaded, so then I pressed the "Switch to/from one-line display" button and still nothing loaded could this be a bug?

**Comment by AlUlkesh** [comment]
Ah, yes, the new Gradio version rears its head. I'll have to adapt the extension to it apparently.

**Comment by AlUlkesh** [comment]
This commit should mostly fix it.

The display switch is working again.

The model switching is also working again. However there's a visual issue, so it's not shown in the top left dropdown. But if you generate, the selected model will be used.
